### ISSUE TITLE
[Bug]: T8520 lock doesn't lock/unlock from HA.

### ISSUE THREAD

**Issue by alexeiw123** [bropat/hassio-eufy-security-ws#11]
### Add-on version

1.5.2

### Architecture

armv7

### HomeAssistant version

2023.6.1

### Operating System type

Other

### Operating system version

HAOS (HA Yellow)

### Describe the bug

When using the [eufy-security-ws](https://github.com/bropat/hassio-eufy-security-ws) add-on v1.5.2 with the [eufy-security](https://github.com/fuatakgun/eufy_security) integration, my T8520 door lock doesn't respond to lock or unlock commands.

If I switch my add-on to the no longer supported [Eufy Security Add-on](https://github.com/fuatakgun/eufy_security_addon) v1.3.0 then the lock command works as you would expect, although the latest version of the integration seems to require the newer add-on to function.

Although the lock/unlock functions don't work, the lock state is reported correctly.

### To reproduce

1. Go to the Eufy T8520 lock device in Home Assistant, dashboard or service dev tools
2. Issue command to lock or unlock as appropriate
3. See that nothing happens

Alternatively,

4. Disable [eufy-security-ws](https://github.com/bropat/hassio-eufy-security-ws)
5. Enable [Eufy Security Add-on](https://github.com/fuatakgun/eufy_security_addon)
6. Roll back [eufy-security](https://github.com/fuatakgun/eufy_security) integration to v6.2.0 or earlier
7. restart HA
8. Follow steps 1-3 and observe expected behaviour

### Screenshots & Logfiles

No applicable logs

### Additional context

[This issue](https://github.com/bropat/eufy-security-ws/issues/209) appears to be the same thing.
I am recreating here as I'm not sure which github project is the correct one to capture and fix the bug through.

**Comment by bropat** [comment]
wrong repo
