### ISSUE TITLE
[Bug]: unable to install addon

### ISSUE THREAD

**Issue by lucianlazar1983** [bropat/hassio-eufy-security-ws#12]
### Add-on version

latest

### Architecture

amd64

### HomeAssistant version

2023.6.1

### Operating System type

Linux

### Operating system version

Hass os

### Describe the bug

Hi, after adding the repository into addons, it is impossible to install the addon with the following error:
Error fetching addon info: Addon 3a26b21d_eufy_security_addon with version latest does not exist in the store
What can I do? Thanks

### To reproduce

1. Go to this repositiry
2. Click on add to homeassistant link
3. Scroll down to install

### Screenshots & Logfiles

![Screenshot_20230614_092413_Home Assistant](https://github.com/bropat/hassio-eufy-security-ws/assets/3727896/61d698e2-f1f3-469c-809a-ef445f555b91)
![Screenshot_20230614_092417_Home Assistant](https://github.com/bropat/hassio-eufy-security-ws/assets/3727896/13ebad1d-3ae5-45b0-a639-0917666ef2f2)

**Comment by TheS1ngularity** [comment]
Hi Lucian, you might have the same issue I had, moving from the previous (deprecated) add-on to this (official) one.
I had to remove the previous addon by uninstalling and remove the repository from Add-Ons as well, but this new add-on was not showing up.
Try a Ctr+F5 refresh on the Add-Ons store page, that might solve it for you.

However, after installing the Add-on, I'm not sure how to configure it, the "Documentation" tab only shows a list of parameters and what they're used for but no mention where to actually add those parameters... Is it in configuration.yaml file? If yes, where exactly? very weird "Documentation" section I have to say. Could've probably taken 2 min to indicate where to set those parameters and save who knows how much time from others...

**Comment by SystemIdleProcess** [comment]
I had this issue initially have uninstalling the previous Eufy Security Add-On and adding the new repository to the store. Had to Ctrl+F5 on the page to refresh it so it showed up properly.
<img width="457" alt="image" src="https://github.com/bropat/hassio-eufy-security-ws/assets/1324919/eca6e79d-dc08-4708-a962-12c1ef347fc3">
