### ISSUE TITLE
[Bug]: Required parameters username and/or password not set

### ISSUE THREAD

**Issue by manic101** [bropat/hassio-eufy-security-ws#18]
### Add-on version

1.5.2

### Architecture

aarch64

### HomeAssistant version

2023.6.2

### Operating System type

Docker

### Operating system version

Raspian 

### Describe the bug

When i create the container, it stops with the following error
curl: (6) Could not resolve host: supervisor
[14:29:34] ERROR: Something went wrong contacting the API
Required parameters username and/or password not set. Starting aborted!

### To reproduce

In docker create container. I have used docker run, compose and portainer all have the same outcome 
services:
  eufy-ws:
    image: bropat/hassio-eufy-security-ws-aarch64:latest
    container_name: eufy-ws
    network_mode: "host"
    volumes:
      - /volume2/docker/eufy-security-ws/data:/data 
    ports:
      - "3000:3000"
    environments:
      - username: itsme@there.com
      - password: myeufy password
      - port: 3000

2. Deploy container and it stops with the following
curl: (6) Could not resolve host: supervisor
[14:29:34] ERROR: Something went wrong contacting the API
Required parameters username and/or password not set. Starting aborted!

**Comment by OrionHeart** [comment]
same hapenning to me, still trying to figure out why its not taking the config.yaml

**Comment by OrionHeart** [comment]
I changed the run.sh to not use bashio::config and directly set the values there and got it installed, not sure if there was any other way

**Comment by githubsharezone** [comment]
i have the same issue . you solved ??

**Comment by camstryker** [comment]
Hey @OrionHeart, do you have an example of how you set the values directly in run.sh? I was trying to do the same on my end, but I'm still receiving the same error.
