### ISSUE TITLE
[Bug]: Error during startup

### ISSUE THREAD

**Issue by RienduPre** [bropat/hassio-eufy-security-ws#2]
### Add-on version

1.3.2

### HomeAssistant version

2023.2.5

### Operating System type

Docker

### Operating system version

HAOS

### Describe the bug

Error during startup (see log)

### To reproduce

Start the add-on

### Screenshots & Logfiles

Log file
`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
/run.sh: line 118:   187 Segmentation fault      /usr/bin/node /usr/src/app/node_modules/eufy-security-ws/dist/bin/server.js --host 0.0.0.0 --config $CONFIG_PATH $DEBUG_OPTION $PORT_OPTION
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

Config file:
username: HA@********
password: *******
country: NL
port: 3200
polling_interval: 10
accept_invitations: false
debug: true
event_duration: 10
stations:
serial_number: T8010P*********
ip_address: 192.168.*.*

**Comment by JoostV** [comment]
I have exactly the same issue. Do you need anything for debugging?

**Comment by JoostV** [comment]
https://en.m.wikipedia.org/wiki/Segmentation_fault

**Comment by bropat** [comment]
@RienduPre @JoostV 

Which image do you use? armhf? aarch64? armv7? amd64? i386?

**Comment by RienduPre** [comment]
I have a odroid N2 this is an ARM  CPU

**Comment by bropat** [comment]
> I have a odroid N2 this is an ARM CPU

Ok, I think the problem is in the AppArmor profile. Couldn't test it for this architecture yet.

**Comment by RienduPre** [comment]
Ok I can help test for you. Let me know what I can do?

**Comment by JoostV** [comment]
Het a odriod n2+, so also arm

**Comment by bropat** [comment]
@RienduPre @JoostV 

**Action plan:**

1. Download [this](https://github.com/bropat/hassio-eufy-security-ws/archive/refs/heads/master.zip) repository 
2. Unpack the zip file
3. Replace the file `apparmor.txt` in the directory `eufy-security-ws` with the following:
    [apparmor.txt](https://github.com/bropat/hassio-eufy-security-ws/files/10828124/apparmor.txt)
4. Copy the directory `eufy-security-ws` to your `addons` directory on your HomeAssistant installation
5. On the HomeAssistent cli launch the following command:
   `ha core restart`
6. On HomeAssistant go to **Settings → Add-ons → Add-on store**. You should now see the following:
    ![image](https://user-images.githubusercontent.com/2305255/221273071-82872579-77cb-4da0-9bdf-bd56a4f95a73.png)
7. Install this add-on, configure it according to documentation and launch the add-on. Now you should not get any `Segmentation fault` anymore.
8. Test everything briefly.
9. Now you need to go to the HomeAssistant operating system and run the following:
    `journalctl _TRANSPORT="audit" -g 'apparmor="ALLOWED"'`
10. Please send me the result of the command.

Thanks!

**Comment by RienduPre** [comment]
Hi,

Add-on is working without errors now :-)

But where do you want me to run step 9.  I only can go the the CLI, and there the command is not working

**Comment by bropat** [comment]
@RienduPre 

Yes, because AppArmor now no longer intervenes and only audits. So you are without protection.
You must follow the documentation below to access the OS and issue the above command:

https://developers.home-assistant.io/docs/operating-system/debugging/

**Comment by RienduPre** [comment]
Hi @bropat 

This is way over my head. And I'm afraid I will ruin my setup.
What exact risk do I have if I don't do this?

**Comment by JoostV** [comment]
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-02-24 21:10:33.894  DEBUG [undefined.constructor] Loaded API_BASE: https://security-app-eu.eufylife.com 
2023-02-24 21:10:33.970  DEBUG [EufySecurity._initializeInternals] Load previous login_hash: 1c38ff04abb0f9235d14e2b3aadcfdd8 
2023-02-24 21:10:33.973  DEBUG [EufySecurity._initializeInternals] Generated new openudid: 180ad1fe592d1eba 
2023-02-24 21:10:33.976  DEBUG [EufySecurity._initializeInternals] Generated new serial_number: bf734e965e85 
2023-02-24 21:10:34.033  DEBUG [EufySecurityServer.start] Starting server on host 0.0.0.0, port 3000 
node:events:491
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at doListen (node:net:1937:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on WebSocketServer instance at:
    at Server.emit (node:events:525:35)
    at emitErrorNT (node:net:1767:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}
Node.js v18.14.2
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by JoostV** [comment]
Didn't stop the other add-on...
Now it is starting

**Comment by JoostV** [comment]
Also do not know how to run the command from step 9

**Comment by bropat** [comment]
Basically, this is just about temporarily enabling the SSH service, then logging in via SSH and running the journalctl command to get the audit logs I need to properly configure AppArmor for the aarch64 architecture. After that you can disable the SSH service as described in the documentation above. Here you basically can't break anything.

**Comment by bropat** [comment]
I have updated the action plan above.

**Comment by JoostV** [comment]
# journalctl _TRANSPORT="audit" -g 'apparmor="ALLOWED"'


-- Boot 674386a07dca48b1b9f18ace3ca719e4 --
-- Boot a738f8e1d4974b8ea3fe7ba13ac54c83 --
-- Boot 674386a07dca48b1b9f18ace3ca719e4 --
-- Boot a738f8e1d4974b8ea3fe7ba13ac54c83 --
-- Boot 674386a07dca48b1b9f18ace3ca719e4 --
-- Boot a738f8e1d4974b8ea3fe7ba13ac54c83 --
-- Boot 404bae153fc245a08370d6dcddb16409 --
-- Boot 6aacaa728cc447ef9766b53fae090f82 --
Feb 24 21:09:19 homeassistant audit[19632]: AVC apparmor="ALLOWED" operation="file_mmap" profile="local_eufy_security_ws//node" name="/usr/bin/node" pid=19632 comm="node" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
Feb 24 21:10:31 homeassistant audit[19922]: AVC apparmor="ALLOWED" operation="file_mmap" profile="local_eufy_security_ws//node" name="/usr/bin/node" pid=19922 comm="node" requested_mask="m" denied_mask="m" fsuid=0 ouid=0
Feb 24 21:15:12 homeassistant audit[20670]: AVC apparmor="ALLOWED" operation="file_mmap" profile="local_eufy_security_ws//node" name="/usr/bin/node" pid=20670 comm="node" requested_mask="m" denied_mask="m" fsuid=0 ouid=0

**Comment by JoostV** [comment]
Hope this gives the needed information

**Comment by bropat** [comment]
@JoostV 
Yes, it does. Thank you very much!

**Comment by RienduPre** [comment]
Hi @bropat 
So you dont my information?

and can you tell me how to get back to the formal addon implementation when the fixed version is available

**Comment by bropat** [comment]
Hi @RienduPre ,

no I don't need them anymore. Thanks anyway.

> can you tell me how to get back to the formal addon implementation when the fixed version is available

Of course:

1. Uninstall the local add-on.
2. Delete the directory `eufy-security-ws` from the `addon` directory of HomeAssistant
3. On the HomeAssistent cli launch the following command:
    `ha core restart`
5. Go back to the official add-on as soon as the new version is released (I will share here).

**Comment by bropat** [comment]
Fixed in version `1.3.4`. Already published.

**Comment by RienduPre** [comment]
Thx for the fast support
