### ISSUE TITLE
[Bug]: Could not fetch changelog

### ISSUE THREAD

**Issue by codyc1515** [bropat/hassio-eufy-security-ws#21]
### Add-on version

1.5.2

### Architecture

armhf

### HomeAssistant version

2023.7.0

### Operating System type

Linux

### Operating system version

HA Operating System 10.3

### Describe the bug

Showing in the logs.

### To reproduce

I think it happened when I pressed check for update button.

### Screenshots & Logfiles

Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:936
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 05:50:51 (1 occurrences)
Last logged: 05:50:51

Could not fetch changelog for 402f1039_eufy_security_ws:

**Comment by codyc1515** [comment]
```
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:548
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 05:50:51 (1 occurrences)
Last logged: 05:50:51

/addons/402f1039_eufy_security_ws/changelog return code 500
```

**Comment by bropat** [comment]
I cannot reproduce this error.
