### ISSUE TITLE
[Bug]: JSON parse error ?

### ISSUE THREAD

**Issue by xvolte** [bropat/hassio-eufy-security-ws#24]
### Add-on version

1.5.2-1

### Architecture

aarch64

### HomeAssistant version

2023.7.2

### Operating System type

Linux

### Operating system version

haos

### Describe the bug

When starting, if i go into log, i got a lot of JSON parse error.

the Yaml configuration IS ok.

`• device.ts:64 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:64:22
• device.ts:63 update
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:63:35
• device.ts:37 initializeState
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:37:14
• device.ts:45 initialize
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:45:14
• eufysecurity.ts:625 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:625:32
2023-07-25 07:38:16.377  ERROR JSON parse error {"r 
 SyntaxError  Unexpected end of JSON input
error stack:
• utils.ts:151 parseJSON
    usr/src/app/node_modules/eufy-security-client/src/utils.ts:151:21
• parameter.ts:45 readValue
    usr/src/app/node_modules/eufy-security-client/src/http/parameter.ts:45:41
• device.ts:132 updateRawProperty
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:132:45
• device.ts:64 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:64:22
• device.ts:63 update
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:63:35
• device.ts:37 initializeState
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:37:14
• device.ts:45 initialize
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:45:14
• eufysecurity.ts:625 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:625:32
2023-07-25 07:38:16.404  ERROR JSON parse error {"r 
 SyntaxError  Unexpected end of JSON input
error stack:
• utils.ts:151 parseJSON
    usr/src/app/node_modules/eufy-security-client/src/utils.ts:151:21
• parameter.ts:45 readValue
    usr/src/app/node_modules/eufy-security-client/src/http/parameter.ts:45:41
• device.ts:132 updateRawProperty
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:132:45
• device.ts:64 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:64:22
• device.ts:63 update
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:63:35
• device.ts:37 initializeState
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:37:14
• device.ts:45 initialize
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:45:14
• eufysecurity.ts:625 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:625:32
2023-07-25 07:38:16.410  ERROR JSON parse error {"r 
 SyntaxError  Unexpected end of JSON input
error stack:
• utils.ts:151 parseJSON
    usr/src/app/node_modules/eufy-security-client/src/utils.ts:151:21
• parameter.ts:45 readValue
    usr/src/app/node_modules/eufy-security-client/src/http/parameter.ts:45:41
• device.ts:132 updateRawProperty
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:132:45
• device.ts:64 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:64:22
• device.ts:63 update
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:63:35
• device.ts:37 initializeState
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:37:14
• device.ts:45 initialize
    usr/src/app/node_modules/eufy-security-client/src/http/device.ts:45:14
• eufysecurity.ts:625 <anonymous>
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:625:32`

### To reproduce

Simply reinstall the addon, put your yaml config file, and start.
then the log screams ... :)

I did a uninstall and fresh reinstall : still the same.

### Screenshots & Logfiles

![image](https://github.com/bropat/hassio-eufy-security-ws/assets/21142611/3769b4de-1b58-49d7-b14f-15df49e0dafe)

![image](https://github.com/bropat/hassio-eufy-security-ws/assets/21142611/ba74c0a8-a64a-44f7-aebb-350a0f4de1bd)

**Comment by wyattofcourse** [comment]
I am having the exact same issue- new installation of Home assistant for the sole purpose of connecting Eufy 2k battery doorbell

**Comment by bropat** [comment]
Please enable the debug option in the settings of `eufy-security-ws`, recreate the problem and send me the debug logs.

**Comment by xvolte** [comment]
Can you tell me where the file is located (with the debug logs?) because i can’t see the error from the preview of the logs if debug enabled

**Comment by wyattofcourse** [comment]
> Can you tell me where the file is located (with the debug logs?) because i can’t see the error from the preview of the logs if debug is enabled : it is way too verbose for the small buffer

Hi @xvolte i think i have figured out where you download logs. its in Home assistant / settings /system  / logs and then in the top right corner you select which app you want the logs from, in this case "eufy-security-ws"

then top right there is a download button. (do this once debug mode is set in the eufy-security-ws addon)

@bropat I have attached my logs if it is of interest, I also have uploaded mine, as I am having a similar error and found this bug report through search. Apologise if that is not how github works, new to github and its customs.


[b1329aaa_eufy_security_ws_2023-07-28T11-58-43.911Z.log](https://github.com/bropat/hassio-eufy-security-ws/files/12194214/b1329aaa_eufy_security_ws_2023-07-28T11-58-43.911Z.log)

**Comment by wyattofcourse** [comment]
@xvolte @bropat just wanted to update and say I am no longer having the JSON parse error, I needed to install an additional addon to fix my setup. @xvolte I don't know if that is helpful for your situation but mine was fixed by installing the Eufy Security Intergration (after installing the addon)
