### ISSUE TITLE
[Bug]: camera image not available 

### ISSUE THREAD

**Issue by vlumikero** [bropat/hassio-eufy-security-ws#3]
### Add-on version

1.3.4

### Architecture

aarch64

### HomeAssistant version

2023.2.5

### Operating System type

Other

### Operating system version

HA Supervised

### Describe the bug

First of all, thanks @bropat for creating this addon. 

I’m not getting an image in the camera entity. How can I troubleshot/help in debugging?

Also, how can I use the last_camera_picture_url combined with my HA URL?

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
Due to changes from Eufy it is currently not possible to get the thumbnails. More about this https://github.com/bropat/eufy-security-client/issues/273.

**Comment by vlumikero** [comment]
What about the camera feed?

**Comment by bropat** [comment]
This add-on alone can only be used via websocket. In order to have full integration in HomeAssistant, you also need [this integration](https://github.com/fuatakgun/eufy_security).
