### ISSUE TITLE
[Bug]:  Startup Failure Couldn't connect to server

### ISSUE THREAD

**Issue by harvindhillon** [bropat/hassio-eufy-security-ws#4]
### Add-on version

1.3.4

### Architecture

amd64

### HomeAssistant version

2023.2.5

### Operating System type

Linux

### Operating system version

22.04.1-Ubuntu

### Describe the bug

I updated from version 1.3.0 by fuaktakgun repo which was working fine.
Steps:
1. Uninstalled the old addon
2. Added new Repo
3. Installed new addon
4. Added Configuration
5. Started Addon

I get the following Error
```
s6-rc:` info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
curl: (7) Couldn't connect to server
[17:57:30] ERROR: Something went wrong contacting the API
Error: failed loading config file /data/eufy-security-ws-config.json
Error: Cannot find module '/data/eufy-security-ws-config.json'
Require stack:
- /usr/src/app/node_modules/eufy-security-ws/dist/bin/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /usr/src/app/node_modules/eufy-security-ws/dist/bin/server.js:26:22
    at Object.<anonymous> (/usr/src/app/node_modules/eufy-security-ws/dist/bin/server.js:78:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/node_modules/eufy-security-ws/dist/bin/server.js' ]
}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Reverting to previous version of 1.3.0 starts up fine.

I have tried the following. 
1. Removing old addon and repo, restarting, adding new repo, restarting, installing new addon.

### To reproduce

1. Uninstalled the old addon
2. Added new Repo
3. Installed new addon
4. Added Configuration
5. Started Addon
6. See error

**Comment by AdsfromOz** [comment]
Able to replicate this with an identical error on HA version: 2023.4.2

@bropat - is there something that we're missing under Docker on Ubuntu 22.04 (22.04.2LTS in my case) - as I don't have any files other than config.json in that folder. Copying config.json to eufy-security-ws-config.json in the data folder presents a different error: 
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
curl: (7) Couldn't connect to server
[12:01:25] ERROR: Something went wrong contacting the API
2023-04-12 02:01:27.168  ERROR Error: 
 Error  EACCES: permission denied, open '/usr/src/app/persistent.json'
details:
{
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/usr/src/app/persistent.json'
}
error stack:
• node:fs:601 openSync
    node:fs:601:3
• node:fs:2249 writeFileSync
    node:fs:2249:35
• eufysecurity.ts:855 writePersistentData
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:855:17
• eufysecurity.ts:137 _initializeInternals
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:137:26
• eufysecurity.ts:85 initialize
    usr/src/app/node_modules/eufy-security-client/src/eufysecurity.ts:85:28
• server.ts:60 <anonymous>
    usr/src/app/node_modules/eufy-security-ws/src/bin/server.ts:60:53
• server.ts:92 <anonymous>
    usr/src/app/node_modules/eufy-security-ws/src/bin/server.ts:92:3
• loader:1254 Module._compile
    node:internal/modules/cjs/loader:1254:14
• loader:1308 Module._extensions..js
    node:internal/modules/cjs/loader:1308:10
• loader:1117 Module.load
    node:internal/modules/cjs/loader:1117:32
Unable to start driver RequestError: getaddrinfo EACCES extend.eufylife.com
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
  code: 'EACCES',
  timings: {
    start: 1681264887218,
    socket: 1681264887222,
    lookup: 1681264887223,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1681264887224,
    abort: undefined,
    phases: {
      wait: 4,
      dns: 1,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 6
    }
  }
}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by nielsaers** [comment]
Anything I can do to help debug this? 
I'm trying to understand what should happen when starting this addon. (I think it should start a docker container if i'm right, but that doesn't happen)

**Comment by dMopp** [comment]
I have the same  :(

**Comment by cmillsy** [comment]
I have the same issue:

> curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
> [17:39:39] ERROR: Something went wrong contacting the API
> Required parameters username and/or password not set. Starting aborted!

after switching to this addon. I have a supervised install.

**Comment by dlasher** [comment]
Same issues here under 2023.6.1 (eufy v6.3.0) - used to work, stopped with 2023.6 install, have removed, re-installed, always stalls out. This is what I see in the log once I add the "hub"

`2023-06-14 15:36:36.919 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 127.0.0.1 for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eufy_security/__init__.py", line 50, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 39, in initialize
    await self._api.connect()
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 72, in connect
    await self._set_schema(SCHEMA_VERSION)
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 150, in _set_schema
    await self._send_message_get_response(OutgoingMessage(OutgoingMessageType.set_api_schema, schema_version=schema_version))
  File "/config/custom_components/eufy_security/eufy_security_api/api_client.py", line 350, in _send_message_get_response
    return await future
           ^^^^^^^^^^^^
custom_components.eufy_security.eufy_security_api.exceptions.FailedCommandException: {'type': 'result', 'success': False, 'messageId': 'set_api_schema.052d01e5372b4f5eba7fa4169715e954', 'errorCode': 'schema_incompatible'}`

**Comment by guneezx** [comment]
I have the same issue:

from eufy-security-ws log:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
curl: (7) Failed to connect to supervisor port 80 after 0 ms: Couldn't connect to server
[02:13:05] ERROR: Something went wrong contacting the API
Required parameters username and/or password not set. Starting aborted!
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

from the host log:
Jun 19 08:06:26 ha-server systemd[1]: var-lib-docker-overlay2-ddbd76e651ac503d75ed5f576dfb4cee171c8d43ef3e567889ea662cff580654\x2dinit-merged.mount: Deactivated successfully.
Jun 19 08:06:26 ha-server kernel: audit: type=1400 audit(1687129586.967:79): apparmor="DENIED" operation="create" class="net" profile="402f1039_eufy_security_ws" pid=104011 comm="curl" family="inet6" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create"
Jun 19 08:06:26 ha-server kernel: audit: type=1400 audit(1687129586.967:80): apparmor="DENIED" operation="create" class="net" profile="402f1039_eufy_security_ws" pid=104011 comm="curl" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
Jun 19 08:06:27 ha-server systemd[1]: run-docker-runtime\x2drunc-moby-0752d29d719494f359d3efadf7b61d759ec5535c17a547e61c90edf3702ad272-runc.OneS0X.mount: Deactivated successfully.
Jun 19 08:06:32 ha-server dockerd[1393]: time="2023-06-19T08:06:32.202973179+09:00" level=info msg="ignoring event" container=0752d29d719494f359d3efadf7b61d759ec5535c17a547e61c90edf3702ad272 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jun 19 08:06:32 ha-server systemd[1]: var-lib-docker-overlay2-ddbd76e651ac503d75ed5f576dfb4cee171c8d43ef3e567889ea662cff580654-merged.mount: Deactivated successfully.

Home Assistant 2023.6.2
Supervisor 2023.06.2
eufy-security-ws 1.3.2
OS Ubuntu 22.04.1

**Comment by honcheng** [comment]
I've also encountered this issue

Home Assistant Supervisor 2023.06.1
eufy-security-ws 1.5.2

I have to run the old Eufy Security Add-on 1.3.0 to get it working

**Comment by dMopp** [comment]
Still the same. @bropat iam still sure this is apparmor related, could you check this please? When i disable apparmor (for testing) it runs fine.
