### ISSUE TITLE
[Bug]: Lock not able to lock/unlock

### ISSUE THREAD

**Issue by TheDarrenn** [bropat/hassio-eufy-security-ws#5]
### Add-on version

1.3.4

### Architecture

aarch64

### HomeAssistant version

2023.3.1

### Operating System type

Other

### Operating system version

not known. using raspberry pi 3 b+

### Describe the bug

I am not able to lock/unlock my eufy door lock T8520

### To reproduce

1. Go to settings > devices & services > eufy integration > doorlock > 
![ScreenShot 06-03-2023at 16 16 30](https://user-images.githubusercontent.com/37628409/223054472-a819fb51-08bf-4b7d-91ad-f07d56945bdc.png)

2. Click on either lock or unlock

3. No response from actual device

### Screenshots & Logfiles

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-03-06 08:02:04.819  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-03-06 08:02:31.017  INFO  Connected to station T8200N00193937AD on host 103.6.150.140 and port 48546 
2023-03-06 08:02:38.828  ERROR MQTT Error 
 Error  Connection refused: Not authorized
details:
{
  code: 5
}
error stack:
• client.js:1388 MqttClient._handleConnack
    usr/src/app/node_modules/mqtt/lib/client.js:1388:17
• client.js:549 MqttClient._handlePacket
    usr/src/app/node_modules/mqtt/lib/client.js:549:12
• client.js:438 work
    usr/src/app/node_modules/mqtt/lib/client.js:438:12
• client.js:452 writable._write
    usr/src/app/node_modules/mqtt/lib/client.js:452:5
• _stream_writable.js:389 doWrite
    usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:389:139
• _stream_writable.js:380 writeOrBuffer
    usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:380:5
• _stream_writable.js:301 Writable.write
    usr/src/app/node_modules/readable-stream/lib/_stream_writable.js:301:11
• readable:766 ondata
    node:internal/streams/readable:766:22
• node:events:513 emit
    node:events:513:28
• readable:324 addChunk
    node:internal/streams/readable:324:12
2023-03-06 08:02:39.093  INFO  MQTT connection closed 
2023-03-06 08:02:42.965  INFO  Push notification connection successfully established 

### Additional context

By physically turning the knob on the door lock updates its current state in HA. Also, I am able to turn on/off my other doorbell and verified using the eufy app.

**Comment by bryan292** [comment]
this is happening to me as well

**Comment by alexeiw123** [comment]
I've got this issue as well.

lock behaves normally if I use the add-on https://github.com/fuatakgun/eufy_security_addon
I can see lock status but can't send lock/unlock using this add-on https://github.com/bropat/hassio-eufy-security-ws
