### ISSUE TITLE
[Bug]: Installation problem

### ISSUE THREAD

**Issue by eranvana** [bropat/hassio-eufy-security-ws#8]
### Add-on version

1.4.1

### Architecture

aarch64

### HomeAssistant version

2023.5.2

### Operating System type

Linux

### Operating system version

linux

### Describe the bug

hello
I have Eufy Doorbell and I installed eufy-security-ws and everything worked great.
Yesterday I removed the and reinstalled and the integration just doesn't connect.
What did I do wrong?
Please help me to install successfully
Thanks

### To reproduce

I have Eufy Doorbell and I installed eufy-security-ws and everything worked great.
Yesterday I removed the and reinstalled and the integration just doesn't connect.

### Screenshots & Logfiles

![345611688_635464201312551_2172202772124321311_n](https://github.com/bropat/hassio-eufy-security-ws/assets/25964123/1bd230fd-82ad-4ce6-a049-d0d0d01ce524)
![346590837_245831544694308_3772604993585645830_n](https://github.com/bropat/hassio-eufy-security-ws/assets/25964123/e8b7c72a-f279-4d6f-b5a0-813fbf36c551)
![346631821_1905646443146933_1923380603464623070_n](https://github.com/bropat/hassio-eufy-security-ws/assets/25964123/66119612-cd31-471d-8d1b-7ed12a1c1eef)
![346324042_1222325821767670_2115166428458746403_n](https://github.com/bropat/hassio-eufy-security-ws/assets/25964123/717d848b-45d7-401f-bdcd-713c8fab2460)
![346331896_970991400921028_9021021547933964800_n](https://github.com/bropat/hassio-eufy-security-ws/assets/25964123/67ce06a4-49bd-4b9b-a6e0-075263bd2806)

**Comment by 0R2YPsALXTVed6y** [comment]
Same here

**Comment by bropat** [comment]
wrong repo
